/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.12
 * Generated at: 2024-11-13 15:47:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.advanced;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.eclipse.help.internal.webapp.data.*;
import org.eclipse.help.webapp.*;

public final class tocView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/advanced/darkTheme.css", Long.valueOf(1725338750000L));
    _jspx_dependants.put("/advanced/../advanced/header.jsp", Long.valueOf(1725338750000L));
    _jspx_dependants.put("/advanced/tocTree.css", Long.valueOf(1725338750000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.eclipse.help.webapp");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.eclipse.help.internal.webapp.data");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 
request.setCharacterEncoding("UTF-8");
boolean isRTL = UrlUtil.isRTL(request, response);
String  direction = isRTL?"rtl":"ltr";

      out.write(" \n");
      out.write(" <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Frameset//EN\" \"http://www.w3.org/TR/html4/frameset.dtd\">\n");
      out.write("<!--\n");
      out.write(" ! Copyright (c) 2000, 2018 IBM Corporation and others.\n");
      out.write(" !\n");
      out.write(" ! This program and the accompanying materials \n");
      out.write(" ! are made available under the terms of the Eclipse Public License 2.0\n");
      out.write(" ! which accompanies this distribution, and is available at\n");
      out.write(" ! https://www.eclipse.org/legal/epl-2.0/\n");
      out.write(" !\n");
      out.write(" ! SPDX-License-Identifier: EPL-2.0\n");
      out.write(" ! \n");
      out.write(" ! Contributors:\n");
      out.write(" !     IBM Corporation - initial API and implementation\n");
      out.write(" -->");
      out.write('\n');
      out.write('\n');
 
	RequestData requestData = new RequestData(application,request, response);
	WebappPreferences prefs = requestData.getPrefs();
	SearchData searchData = new SearchData(application,request, response);

      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"");
      out.print(ServletResources.getString("locale", request));
      out.write("\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("<title>");
      out.print(ServletResources.getString("Content", request));
      out.write("</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("/*******************************************************************************\n");
      out.write(" * Copyright (c) 2006 IBM Corporation and others.\n");
      out.write(" *\n");
      out.write(" * This program and the accompanying materials \n");
      out.write(" * are made available under the terms of the Eclipse Public License 2.0\n");
      out.write(" * which accompanies this distribution, and is available at\n");
      out.write(" * https://www.eclipse.org/legal/epl-2.0/\n");
      out.write(" *\n");
      out.write(" * SPDX-License-Identifier: EPL-2.0\n");
      out.write(" * \n");
      out.write(" * Contributors:\n");
      out.write(" *     IBM Corporation - initial API and implementation\n");
      out.write(" *******************************************************************************/\n");
      out.write(" \n");
      out.write(" BODY {\n");
      out.write("	font: ");
      out.print(prefs.getViewFont());
      out.write(";\n");
      out.write("	font-size: .875rem;\n");
      out.write("	margin-top:2px;\n");
      out.write("	margin-");
      out.print(isRTL?"right":"left");
      out.write(":5px;\n");
      out.write("	padding:0;\n");
      out.write("	border:0;\n");
      out.write("	");
      out.print(prefs.getViewBackgroundStyle());
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("#root {\n");
      out.write("	margin-top:0px;\n");
      out.write("	margin-");
      out.print(isRTL?"right":"left");
      out.write(":0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("DIV.root {\n");
      out.write("    font-weight:bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("DIV.visible, DIV.unopened { \n");
      out.write("	border-width:0; \n");
      out.write("	margin-");
      out.print(isRTL?"right":"left");
      out.write(":1.5em; \n");
      out.write("	font-weight:normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write("DIV.group { \n");
      out.write("	border-width:0; \n");
      out.write("	margin-");
      out.print(isRTL?"right":"left");
      out.write(":0; \n");
      out.write("}\n");
      out.write("  \n");
      out.write("DIV.hidden {\n");
      out.write("	display:none; \n");
      out.write("}\n");
      out.write("\n");
      out.write("DIV.visible, DIV.root {  \n");
      out.write("    margin-top:1px; \n");
      out.write("}\n");
      out.write("\n");
      out.write("SPAN.item{\n");
      out.write("    white-space: nowrap;\n");
      out.write("}\n");
      out.write("\n");
      out.write("IMG {\n");
      out.write("	border:0px;\n");
      out.write("	margin:0px;\n");
      out.write("	padding:0px;\n");
      out.write("	margin-");
      out.print(isRTL?"left":"right");
      out.write(":4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("IMG.expander, IMG.h {\n");
      out.write("    margin-top:4px;\n");
      out.write("    margin-bottom:2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("A {\n");
      out.write("	text-decoration:none; \n");
      out.write("	color:WindowText;\n");
      out.write("	padding-");
      out.print(isRTL?"left":"right");
      out.write(":2px;\n");
      out.write("	/* this works in ie5.5, but not in ie5.0  */\n");
      out.write("	white-space: nowrap;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".showall {\n");
      out.write("    text-decoration:underline; \n");
      out.write("    color:#0066FF; \n");
      out.write("	cursor:pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("A:hover{\n");
      out.write("	text-decoration:underline; \n");
      out.write("}\n");
      out.write("\n");
      out.write("A.active{ \n");
      out.write("	color:HighlightText;\n");
      out.write("	background:Highlight;\n");
      out.write("	width:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("A.active:hover{\n");
      out.write("	text-decoration:underline; \n");
      out.write("}\n");
      out.write("\n");
      out.write("A.nolink {\n");
      out.write("	text-decoration:none; \n");
      out.write("}\n");
      out.write("\n");
      out.write("A.nolink:link, A.nolink:visited {\n");
      out.write("	color:WindowText;\n");
      out.write("}\n");
      out.write("\n");
      out.write("A.nolink:hover {\n");
      out.write("	text-decoration:none; \n");
      out.write("}\n");
      out.write("\n");
      out.write(".h {\n");
      out.write("	visibility:hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (prefers-color-scheme: dark) {\n");
      out.write("	body { \n");
      out.write("		color: #f0f0f0; \n");
      out.write("		background: #3d3d3d;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#titleText,\n");
      out.write("	#searchLabel,\n");
      out.write("	#scopeLabel,\n");
      out.write("	#scope,\n");
      out.write("	a,\n");
      out.write("	a.active\n");
      out.write("	a.nolink:link, \n");
      out.write("	a.nolink:visited {\n");
      out.write("		color:#ffffff;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.button a:hover, .buttonMenu a:hover { \n");
      out.write("		border-top:1px solid #3d3d3d; \n");
      out.write("		border-");
      out.print(isRTL?"right":"left");
      out.write(":1px solid #3d3d3d; \n");
      out.write("		border-");
      out.print(isRTL?"left":"right");
      out.write(":1px solid #3d3d3d; \n");
      out.write("		border-bottom:1px solid #3d3d3d;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	table {\n");
      out.write("		background:#3d3d3d;\n");
      out.write("	}\n");
      out.write("	.tab {\n");
      out.write("		background:#7b7c7b\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	form {\n");
      out.write("		background:#3d3d3d;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.separator {\n");
      out.write("\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	input{\n");
      out.write("		background:#a0a0a0;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.button a, .buttonMenu a { \n");
      out.write("		border:1px solid #3d3d3d;;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/* darken images to add some comfort while reading in dark theme */\n");
      out.write("	img {\n");
      out.write("		opacity: .75;\n");
      out.write("		transition: opacity .5s ease-in-out;\n");
      out.write("	}\n");
      out.write("	img:hover {\n");
      out.write("		opacity: 1;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.location, .location a {\n");
      out.write("		color:#00cc66;\n");
      out.write("	}\n");
      out.write("}");
      out.write('\n');
      out.write(' ');
      out.write('\n');
      out.write("\n");
      out.write("</style>  \n");
      out.write("    \n");
      out.write("<base target=\"ContentViewFrame\">\n");
      out.write("<script type=\"text/javascript\" src=\"helptree.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"helptreechildren.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"xmlajax.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"tocTree.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"view.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("// Preload images\n");
      out.write("var imagesDirectory = \"");
      out.print(prefs.getImagesDirectory());
      out.write("\";\n");
      out.write("minus = new Image();\n");
      out.write("minus.src = imagesDirectory + \"/minus.svg\";\n");
      out.write("plus = new Image();\n");
      out.write("plus.src = imagesDirectory + \"/plus.svg\";\n");
      out.write("toc_open_img = new Image();\n");
      out.write("toc_open_img.src = imagesDirectory + \"/toc_open.svg\";\n");
      out.write("toc_closed_img = new Image();\n");
      out.write("toc_closed_img.src = imagesDirectory + \"/toc_closed.svg\";\n");
      out.write("folder_img = new Image();\n");
      out.write("folder_img.src = imagesDirectory + \"/container_obj.svg\";\n");
      out.write("folder_topic = new Image();\n");
      out.write("folder_topic.src = imagesDirectory + \"/container_topic.svg\";\n");
      out.write("topic_img = new Image();\n");
      out.write("topic_img.src = imagesDirectory + \"/topic.svg\";\n");
      out.write("\n");
      out.write("var altTopic = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("altTopic", request)));
      out.write("\";\n");
      out.write("var altContainer = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("altContainer", request)));
      out.write("\";\n");
      out.write("var altContainerTopic = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("altContainerTopic", request)));
      out.write("\";\n");
      out.write("var altBookClosed = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("bookClosed", request)));
      out.write("\";\n");
      out.write("var altBookOpen = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("bookOpen", request)));
      out.write("\";\n");
      out.write("var altPlus = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("expandTopicTitles", request)));
      out.write("\";\n");
      out.write("var altMinus = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("collapseTopicTitles", request)));
      out.write("\";\n");
      out.write("var loadingMessage = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("Loading", request)));
      out.write("\";\n");
      out.write("var cookiesRequired = \"");
      out.print(UrlUtil.JavaScriptEncode(ServletResources.getString("cookiesRequired", request)));
      out.write("\";\n");
      out.write("\n");
      out.write("var isIE = navigator.userAgent.indexOf('MSIE') != -1;\n");
      out.write("var isRTL = ");
      out.print(isRTL);
      out.write(";\n");
      out.write("\n");
      out.write("var tocTitle = \"\";\n");
      out.write("var tocId = \"\";\n");
      out.write("	\n");
      out.write("function onloadHandler()\n");
      out.write("{\n");
      out.write("    setRootAccessibility();\n");
      out.write("	loadChildren(null);\n");
      out.write("	\n");
      out.write("	// Set prefix for AJAX calls by removing tocView.jsp from location\n");
      out.write("	var locationHref = window.location.href;\n");
      out.write("    var slashAdvanced = locationHref.lastIndexOf('/tocView.jsp');\n");
      out.write("    if(slashAdvanced > 0) {\n");
      out.write("	    setAjaxPrefix(locationHref.substr(0, slashAdvanced));\n");
      out.write("	}\n");

    if (request.getParameter("topic") != null) {
        TocData data = new TocData(application,request, response);
	    if (data.getSelectedToc() != -1) {

      out.write("\n");
      out.write("	var tocTopic = \"");
      out.print(UrlUtil.JavaScriptEncode(data.getTocDescriptionTopic(data.getSelectedToc())));
      out.write("\";\n");
      out.write("	var topicSelected=false;\n");
      out.write("	// select specified topic, or else the book\n");
      out.write("	var topic = \"");
      out.print(UrlUtil.JavaScriptEncode(data.getSelectedTopicWithPath()));
      out.write("\";\n");
      out.write("	if (topic != \"about:blank\" && topic != tocTopic) {\n");
      out.write("		if (topic.indexOf(window.location.protocol) != 0 && topic.length > 2) {\n");
      out.write("			// remove the .. from topic\n");
      out.write("			topic = topic.substring(2);\n");
      out.write("			// remove advanced/tocView.jsp from path to obtain contextPath\n");
      out.write("			var contextPath = window.location.pathname;\n");
      out.write("			var slash = contextPath.lastIndexOf('/');\n");
      out.write("			if(slash > 0) {\n");
      out.write("				slash = contextPath.lastIndexOf('/', slash-1);\n");
      out.write("				if(slash >= 0) {\n");
      out.write("					contextPath = contextPath.substr(0, slash);\n");
      out.write("					topic = window.location.protocol + \"//\" +window.location.host + contextPath + topic;\n");
      out.write("				}\n");
      out.write("			}			\n");
      out.write("		}\n");
      out.write("		topicSelected = selectTopic(topic);\n");
      out.write("	} \n");

	    }
	} else if (!"true".equalsIgnoreCase(request.getParameter("collapse"))) {

      out.write("   \n");
      out.write("        if (isAutosynchEnabled()) {\n");
      out.write("	        selectTopic(\"");
      out.print(prefs.getHelpHome());
      out.write("\", true);\n");
      out.write("	    }\n");

	} 

      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function onunloadHandler() {\n");

// for large books, we want to avoid a long unload time
if (requestData.isIE()){

      out.write("\n");
      out.write("	document.body.innerHTML = \"\";\n");

}

      out.write("\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body dir=\"");
      out.print(direction);
      out.write("\" onload=\"onloadHandler()\" onunload=\"onunloadHandler()\">\n");

    if (searchData.isScopeActive()) {

      out.write("\n");
      out.write("<p>\n");
      out.print( UrlUtil.htmlEncode(searchData.getScopeActiveMessage()) );
      out.write("\n");
      out.write("<a class=\"showall\" onclick=\"showAll();\" >");
      out.print(ServletResources.getString("showAllLink", request));
      out.write("</a>\n");
      out.write("</p>\n");

    }

      out.write("\n");
      out.write("\n");
      out.write("  <DIV class = \"group\" id = \"wai_application\" aria-label = \"Table of contents container\">\n");
      out.write("    <DIV class = \"root\" aria-label = \"Table of contents\" id = \"tree_root\">\n");
      out.write("    </DIV>\n");
      out.write("  </DIV>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
