/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.12
 * Generated at: 2024-11-13 15:47:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.advanced;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.eclipse.help.internal.webapp.data.*;
import org.eclipse.help.webapp.*;

public final class toolbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/advanced/darkTheme.css", Long.valueOf(1725338750000L));
    _jspx_dependants.put("/advanced/header.jsp", Long.valueOf(1725338750000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.eclipse.help.webapp");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.eclipse.help.internal.webapp.data");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 
request.setCharacterEncoding("UTF-8");
boolean isRTL = UrlUtil.isRTL(request, response);
String  direction = isRTL?"rtl":"ltr";

      out.write(" \n");
      out.write(" <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Frameset//EN\" \"http://www.w3.org/TR/html4/frameset.dtd\">\n");
      out.write("<!--\n");
      out.write(" ! Copyright (c) 2000, 2018 IBM Corporation and others.\n");
      out.write(" !\n");
      out.write(" ! This program and the accompanying materials \n");
      out.write(" ! are made available under the terms of the Eclipse Public License 2.0\n");
      out.write(" ! which accompanies this distribution, and is available at\n");
      out.write(" ! https://www.eclipse.org/legal/epl-2.0/\n");
      out.write(" !\n");
      out.write(" ! SPDX-License-Identifier: EPL-2.0\n");
      out.write(" ! \n");
      out.write(" ! Contributors:\n");
      out.write(" !     IBM Corporation - initial API and implementation\n");
      out.write(" -->");
      out.write('\n');
      out.write('\n');
 
	ToolbarData data = new ToolbarData(application,request, response);
	WebappPreferences prefs = data.getPrefs();

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"");
      out.print(ServletResources.getString("locale", request));
      out.write("\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("<title>");
      out.print(ServletResources.getString("Toolbar", request));
      out.write("</title>\n");
      out.write(" \n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/* need this one for Mozilla */\n");
      out.write("HTML { \n");
      out.write("	margin:0px;\n");
      out.write("	padding:0px;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("BODY {\n");
      out.write("	background:");
      out.print(prefs.getToolbarBackground());
      out.write(";\n");
      out.write("}\n");
      out.write("\n");
      out.write("#titleText {\n");
      out.write("	font-weight:bold;\n");
      out.write("	color:WindowText;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("    cursor : default\n");
      out.write("}\n");
      out.write(" \n");
      out.write(".buttonOn a { \n");
      out.write("	display:block;\n");
      out.write("	margin-left:2px;\n");
      out.write("	margin-right:2px;\n");
      out.write("	width:");
      out.print(data.isMozilla()?18:20);
      out.write("px;\n");
      out.write("	height:");
      out.print(data.isMozilla()?18:20);
      out.write("px;\n");
      out.write("	border:1px solid Highlight;\n");
 
if (data.isIE()){

      out.write("\n");
      out.write("	writing-mode:tb-rl; ");
      out.write('\n');

}

      out.write("	\n");
      out.write("    vertical-align:middle;\n");
 
    String bg = prefs.getViewBackgroundStyle();
    if (bg.length() == 0) {

      out.write("\n");
      out.write("	background: Window;\n");

    } else {

      out.write("\n");
      out.write("   ");
      out.print(bg);
      out.write('\n');

}

      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button a, .buttonMenu a { \n");
      out.write("	display:block;\n");
      out.write("	margin-left:2px;\n");
      out.write("	margin-right:2px;\n");
      out.write("	height:");
      out.print(data.isMozilla()?18:20);
      out.write("px;\n");
      out.write("	border:1px solid ");
      out.print(prefs.getToolbarBackground());
      out.write(';');
      out.write('\n');
 
if (data.isIE()){

      out.write("\n");
      out.write("	writing-mode:tb-rl; ");
      out.write('\n');

}

      out.write("	\n");
      out.write("	vertical-align:middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button a {\n");
      out.write("	width:");
      out.print(data.isMozilla()?18:20);
      out.write("px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".buttonMenu a {\n");
      out.write("	width:");
      out.print(data.isMozilla()?30:32);
      out.write("px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".buttonHidden a { \n");
      out.write("	display:none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button a:hover, .buttonMenu a:hover { \n");
      out.write("	border-top:1px solid ButtonHighlight; \n");
      out.write("	border-");
      out.print(isRTL?"right":"left");
      out.write(":1px solid ButtonHighlight; \n");
      out.write("	border-");
      out.print(isRTL?"left":"right");
      out.write(":1px solid ButtonShadow; \n");
      out.write("	border-bottom:1px solid ButtonShadow;\n");
      out.write("}\n");
      out.write("\n");
 if (data.isIE() || data.isMozilla() && "1.2.1".compareTo(data.getMozillaVersion()) <=0){
// maximize (last) button should not jump

      out.write('\n');
      out.write('\n');
}
      out.write("\n");
      out.write("\n");
      out.write(".separator {\n");
      out.write("	background-color: ThreeDShadow;\n");
      out.write("	height:100%;\n");
      out.write("	width: 1px;\n");
      out.write("	border-top:2px solid ");
      out.print(prefs.getToolbarBackground());
      out.write(";\n");
      out.write("	border-bottom:2px solid ");
      out.print(prefs.getToolbarBackground());
      out.write(";\n");
      out.write("	border-left:3px solid ");
      out.print(prefs.getToolbarBackground());
      out.write(";\n");
      out.write("	border-right:3px solid ");
      out.print(prefs.getToolbarBackground());
      out.write(";\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("#container {\n");
      out.write("	border-bottom:1px solid ThreeDShadow;\n");

if (data.isIE()) {

      out.write(' ');
      out.write('\n');

}else if (data.isMozilla()){

      out.write("\n");
      out.write("	border-top:1px solid ThreeDShadow;\n");
      out.write("	height:24px;\n");

}

      out.write("\n");
      out.write("}\n");
      out.write("\n");

// workaround for adding right border on mozilla (ugly..)
if (data.isMozilla() && "content".equals(request.getParameter("toolbar"))) { 

      out.write("\n");
      out.write("\n");
      out.write("/* need this one for Mozilla */\n");
      out.write("HTML { \n");
      out.write("	margin:0px;\n");
      out.write("	padding:0px;\n");
      out.write("}\n");

}

      out.write('\n');
      out.write('\n');
      out.write("@media (prefers-color-scheme: dark) {\n");
      out.write("	body { \n");
      out.write("		color: #f0f0f0; \n");
      out.write("		background: #3d3d3d;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#titleText,\n");
      out.write("	#searchLabel,\n");
      out.write("	#scopeLabel,\n");
      out.write("	#scope,\n");
      out.write("	a,\n");
      out.write("	a.active\n");
      out.write("	a.nolink:link, \n");
      out.write("	a.nolink:visited {\n");
      out.write("		color:#ffffff;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.button a:hover, .buttonMenu a:hover { \n");
      out.write("		border-top:1px solid #3d3d3d; \n");
      out.write("		border-");
      out.print(isRTL?"right":"left");
      out.write(":1px solid #3d3d3d; \n");
      out.write("		border-");
      out.print(isRTL?"left":"right");
      out.write(":1px solid #3d3d3d; \n");
      out.write("		border-bottom:1px solid #3d3d3d;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	table {\n");
      out.write("		background:#3d3d3d;\n");
      out.write("	}\n");
      out.write("	.tab {\n");
      out.write("		background:#7b7c7b\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	form {\n");
      out.write("		background:#3d3d3d;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.separator {\n");
      out.write("\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	input{\n");
      out.write("		background:#a0a0a0;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.button a, .buttonMenu a { \n");
      out.write("		border:1px solid #3d3d3d;;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/* darken images to add some comfort while reading in dark theme */\n");
      out.write("	img {\n");
      out.write("		opacity: .75;\n");
      out.write("		transition: opacity .5s ease-in-out;\n");
      out.write("	}\n");
      out.write("	img:hover {\n");
      out.write("		opacity: 1;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	.location, .location a {\n");
      out.write("		color:#00cc66;\n");
      out.write("	}\n");
      out.write("}");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");

    String[] scripts = data.getScriptFiles();
    for (int s = 0; s < scripts.length; s++) {
        String path = scripts[s];

      out.write("\n");
      out.write("    <script type=\"text/javascript\" src = \"");
      out.print(path);
      out.write("\" ></script>\n");

    }

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var bRestore = false;\n");
      out.write("// Preload images\n");

ToolbarButton[] buttons = data.getButtons();
for (int i=0; i<buttons.length; i++) {
	if (!buttons[i].isSeparator()) {

      out.write("\n");
      out.write("	var ");
      out.print(buttons[i].getName());
      out.write(" = new Image();\n");
      out.write("	");
      out.print(UrlUtil.JavaScriptEncode(buttons[i].getName()));
      out.write(".src = \"");
      out.print(UrlUtil.JavaScriptEncode(buttons[i].getImage()));
      out.write('"');
      out.write(';');
      out.write('\n');

	}
}

      out.write("\n");
      out.write("\n");
      out.write("function setTitle(label)\n");
      out.write("{\n");
      out.write("	if( label == null) label = \"\";\n");
      out.write("	var title = document.getElementById(\"titleText\");\n");
      out.write("	if (title == null) return;\n");
      out.write("	var text = title.lastChild;\n");
      out.write("	if (text == null) return;\n");
      out.write("	text.nodeValue = label;\n");
      out.write("}\n");
      out.write("\n");
 if (data.isIE()
	|| data.isMozilla() && "1.2.1".compareTo(data.getMozillaVersion()) <=0
	|| (data.isSafari() && "120".compareTo(data.getSafariVersion()) <= 0) ){

      out.write("\n");
      out.write("function registerMaximizedChangedListener(){\n");
      out.write("	// get to the frameset\n");
      out.write("	var p = parent;\n");
      out.write("	while (p && !p.registerMaximizeListener) {	   \n");
      out.write("	    if (p === p.parent)  {\n");
      out.write("	        return;\n");
      out.write("        }\n");
      out.write("		p = p.parent;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if (p!= null){\n");
      out.write("		p.registerMaximizeListener('");
      out.print(UrlUtil.JavaScriptEncode(data.getName()));
      out.write("Toolbar', maximizedChanged);\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("registerMaximizedChangedListener();\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * Handler for double click: maximize/restore this view\n");
      out.write(" * Note: Mozilla browsers prior to 1.2.1 do not support programmatic frame resizing well.\n");
      out.write(" */\n");
      out.write("function mouseDblClickHandler(e) {\n");
      out.write("	// ignore double click on buttons\n");
      out.write("	var target=");
      out.print(data.isIE()?"window.event.srcElement":"e.target");
      out.write(";\n");
      out.write("	if (target.tagName && (target.tagName == \"A\" || target.tagName == \"IMG\"))\n");
      out.write("		return;\n");
      out.write("	toggleFrame();\n");
      out.write("	return false;\n");
      out.write("}		\n");
      out.write("function restore_maximize(button)\n");
      out.write("{\n");
      out.write("	toggleFrame();\n");
      out.write("	if (button && document.getElementById(button)){\n");
      out.write("		document.getElementById(button).blur();\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function toggleFrame(){\n");
      out.write("	// get to the frameset\n");
      out.write("	var p = parent;\n");
      out.write("	while (p && !p.toggleFrame)  {	   \n");
      out.write("	    if (p === p.parent)  {\n");
      out.write("	        return;\n");
      out.write("        }\n");
      out.write("		p = p.parent;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if (p!= null){\n");
      out.write("		p.toggleFrame('");
      out.print(UrlUtil.JavaScriptEncode(data.getTitle()));
      out.write("');\n");
      out.write("	}\n");
      out.write("	document.selection.clear;	\n");
      out.write("}\n");
      out.write("\n");
      out.write("function maximizedChanged(maximizedNotRestored){\n");
      out.write("	if(maximizedNotRestored){\n");
      out.write("		document.getElementById(\"maximize_restore\").src=\"");
      out.print(data.getRestoreImage());
      out.write("\";\n");
      out.write("		document.getElementById(\"maximize_restore\").setAttribute(\"title\", \n");
      out.write("		    \"");
      out.print(UrlUtil.JavaScriptEncode(data.getRestoreTooltip()));
      out.write("\");\n");
      out.write("		document.getElementById(\"maximize_restore\").setAttribute(\"alt\", \n");
      out.write("		    \"");
      out.print(UrlUtil.JavaScriptEncode(data.getRestoreTooltip()));
      out.write("\");\n");
      out.write("		bRestore = true;\n");
      out.write("	}else{\n");
      out.write("		document.getElementById(\"maximize_restore\").src=\"");
      out.print(data.getMaximizeImage());
      out.write("\";\n");
      out.write("		document.getElementById(\"maximize_restore\").setAttribute(\"title\", \n");
      out.write("		    \"");
      out.print(UrlUtil.JavaScriptEncode(data.getMaximizeTooltip()));
      out.write("\");\n");
      out.write("		document.getElementById(\"maximize_restore\").setAttribute(\"alt\", \n");
      out.write("		    \"");
      out.print(UrlUtil.JavaScriptEncode(data.getMaximizeTooltip()));
      out.write("\");\n");
      out.write("		bRestore = false;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.print(( data.isIE() || data.isSafari() )?
	"document.ondblclick = mouseDblClickHandler;"
:
	"document.addEventListener('dblclick', mouseDblClickHandler, true);");
      out.write('\n');
}
      out.write("\n");
      out.write("\n");
      out.write("function setButtonState(buttonName, pressed) {\n");
      out.write("	if(!document.getElementById(\"tdb_\"+buttonName))\n");
      out.write("		return;\n");
      out.write("	if (pressed == \"hidden\")\n");
      out.write("		document.getElementById(\"tdb_\"+buttonName).className=\"buttonHidden\";\n");
      out.write("	else if(pressed == true)\n");
      out.write("		document.getElementById(\"tdb_\"+buttonName).className=\"buttonOn\";\n");
      out.write("	else\n");
      out.write("		document.getElementById(\"tdb_\"+buttonName).className=\"button\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("function setWindowStatus(buttonName){\n");
      out.write("	");

	for (int i=0; i<buttons.length; i++) {
		String name = buttons[i].getName();
      out.write("\n");
      out.write("		if (buttonName == \"");
      out.print(UrlUtil.JavaScriptEncode(name));
      out.write("\"){\n");
      out.write("			if (buttonName == \"maximize_restore\"){\n");
      out.write("				if (bRestore){\n");
      out.write("					window.status = \"");
      out.print(UrlUtil.JavaScriptEncode(data.getRestoreTooltip()));
      out.write("\";\n");
      out.write("				}else{\n");
      out.write("					window.status = \"");
      out.print(UrlUtil.JavaScriptEncode(data.getMaximizeTooltip()));
      out.write("\";\n");
      out.write("				}\n");
      out.write("			}else{\n");
      out.write("				window.status = \"");
      out.print(UrlUtil.JavaScriptEncode(buttons[i].getTooltip()));
      out.write("\";\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	");
	
	}
	
      out.write("\n");
      out.write("}\n");
      out.write("\n");

if (data.hasMenu()) {

      out.write("\n");
      out.write("\n");
      out.write("function menu(button, param) {\n");
      out.write("	var doc = parent.frames[1].document;\n");
      out.write("	if (!doc.getElementById(\"menu\")) {\n");
      out.write("		var menu = doc.createElement(\"div\");\n");
      out.write("		menu.id = \"menu\";\n");
      out.write("		menu.srcButton = button;\n");
      out.write("		menu.onmouseout = menuExit;\n");
      out.write("		menu.onkeydown = menuKey;\n");
      out.write("		\n");
      out.write("		menu.style.padding = \"2px 2px 2px 2px\";\n");
      out.write("		menu.style.position = \"absolute\";\n");
      out.write("		menu.style.");
      out.print(isRTL ? "left" : "right");
      out.write(" = \"0px\";\n");
      out.write("		menu.style.top = \"0px\";\n");
      out.write("		menu.style.background = \"");
      out.print(prefs.getToolbarBackground());
      out.write("\";\n");
      out.write("		menu.style.font = \"");
      out.print(prefs.getToolbarFont());
      out.write("\";\n");
      out.write("		menu.style.fontSize = \".875rem\";\n");
      out.write("		menu.style.border");
      out.print(isRTL ? "Right" : "Left");
      out.write(" = \"1px solid ThreeDShadow\";\n");
      out.write("		menu.style.borderBottom = \"1px solid ThreeDShadow\";\n");
      out.write("\n");
      out.write("		var entries = param.split(\",\");\n");
      out.write("		for (var i=0;i<entries.length;++i) {\n");
      out.write("			var properties = entries[i].split(\"=\");\n");
      out.write("			var anchor = doc.createElement(\"a\");\n");
      out.write("			var text = doc.createTextNode(properties[0]);\n");
      out.write("			anchor.title = properties[0];\n");
      out.write("			anchor.appendChild(text);\n");
      out.write("			anchor.href = \"javascript:parent.frames[0].closeMenu(),parent.frames[0].\" + properties[1];\n");
      out.write("			anchor.target = \"_self\";\n");
      out.write("			anchor.onmouseover = itemEnter;\n");
      out.write("			anchor.onmouseout = itemExit;\n");
      out.write("			anchor.onfocus = itemEnter;\n");
      out.write("			anchor.onblur = itemExit;\n");
      out.write("			anchor.style.display = \"block\";\n");
      out.write("			anchor.style.cursor = \"default\";\n");
      out.write("			anchor.style.textDecoration = \"none\";\n");
      out.write("			anchor.style.padding = \"4px 4px 4px 4px\";\n");
      out.write("			anchor.style.background = \"transparent\";\n");
      out.write("			anchor.style.color = \"WindowText\";\n");
      out.write("			menu.appendChild(anchor);\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		doc.body.appendChild(menu);\n");
      out.write("		menu.focus();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	if (button && document.getElementById(button)) {\n");
      out.write("		var buttonElem = document.getElementById(button);\n");
      out.write("		buttonElem.blur();\n");
      out.write("		buttonElem.firstChild.title = \"\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function menuKey(e) {\n");
      out.write("	var key;\n");
      out.write("	if (!e) var e = parent.frames[parent.frames.length - 1].window.event;\n");
      out.write("	if (e.keyCode) key = e.keyCode;\n");
      out.write("	else if (e.which) key = e.which;\n");
      out.write("    var src = e.srcElement ? e.srcElement : e.target;\n");
      out.write("\n");
      out.write("  	if (key == 38) { // Up arrow\n");
      out.write("  		if (src.id != \"menu\" && src.previousSibling) {\n");
      out.write("  			src.previousSibling.focus();\n");
      out.write("  		}\n");
      out.write("  	}\n");
      out.write("  	else if (key == 40) { // Down arrow\n");
      out.write("  		if (src.id == \"menu\") {\n");
      out.write("  			src.firstChild.focus();\n");
      out.write("  		}\n");
      out.write("  		else if (src.nextSibling) {\n");
      out.write("  			src.nextSibling.focus();\n");
      out.write("  		}\n");
      out.write("  	}\n");
      out.write("  	else if (key == 27) { // Esc\n");
      out.write("  		closeMenu();\n");
      out.write("  	}\n");
      out.write("  	else {\n");
      out.write("  		return true;\n");
      out.write("  	}\n");
      out.write("  	return false;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function closeMenu() {\n");
      out.write("    parent.frames[parent.frames.length - 1].window.status = \"\";\n");
      out.write("	var menu = parent.frames[1].document.getElementById(\"menu\");\n");
      out.write("	menu.parentNode.removeChild(menu);\n");
      out.write("\n");
      out.write("	var img = document.getElementById(menu.srcButton).firstChild;\n");
      out.write("	img.title = img.alt;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function itemEnter(e) {\n");
      out.write("    this.style.background = \"Highlight\";\n");
      out.write("    this.style.color = \"HighlightText\";\n");
      out.write("    parent.frames[parent.frames.length - 1].window.status = this.firstChild.nodeValue;\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function itemExit(e) {\n");
      out.write("    this.style.background = \"transparent\";\n");
      out.write("    this.style.color = \"WindowText\";\n");
      out.write("    parent.frames[parent.frames.length - 1].window.status = \"\";\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function menuExit(e) {\n");
      out.write("	if (!e) var e = parent.frames[parent.frames.length - 1].window.event;\n");
      out.write("    var target = e.relatedTarget ? e.relatedTarget : e.toElement;\n");
      out.write("    while (target && target != this)\n");
      out.write("         target = target.parentNode;\n");
      out.write("    if (target == this) return;\n");
      out.write("    closeMenu();\n");
      out.write("}\n");
      out.write("\n");

}

      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");

if (data.getScript() != null) {

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(UrlUtil.htmlEncode(data.getScript()));
      out.write("\"></script>\n");

}

      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write(" \n");

if(buttons.length > 0){

      out.write("\n");
      out.write("	<body dir=\"");
      out.print(direction);
      out.write('"');
      out.write('>');
      out.write('\n');

}else{

      out.write("\n");
      out.write("	<body dir=\"");
      out.print(direction);
      out.write("\" tabIndex=\"-1\">\n");

}

      out.write("\n");
      out.write("\n");
      out.write("<table id=\"container\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"100%\" style='padding-");
      out.print(isRTL?"right":"left");
      out.write(':');
      out.print(data.isIE()?"5px":"8px");
      out.write(";'>\n");
      out.write("\n");
      out.write("	<tr>\n");
      out.write("		<td nowrap style=\"font: ");
      out.print(prefs.getToolbarFont());
      out.write("; font-size: .875rem\" valign=\"middle\">\n");
      out.write("			<div id=\"titleTextTableDiv\" style=\"overflow:hidden; height:22px;\"><table><tr><td nowrap style=\"font:");
      out.print(prefs.getToolbarFont());
      out.write(";font-size:1em\"><div id=\"titleText\" >&nbsp;");
      out.print(UrlUtil.htmlEncode(data.getTitle()));
      out.write("</div></td></tr></table>\n");
      out.write("			</div>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<div style=\"position:absolute; top:1px; ");
      out.print(isRTL?"left":"right");
      out.write(":0px;\">\n");
      out.write("		<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" height=\"100%\">\n");
      out.write("			<tr>\n");
      out.write("				<td align=\"");
      out.print(isRTL?"left":"right");
      out.write("\">\n");
      out.write("					<table align=\"");
      out.print(isRTL?"left":"right");
      out.write("\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"100%\">\n");
      out.write("					<tr>\n");

	for (int i=0; i<buttons.length; i++) {
		if (buttons[i].isSeparator()) {

      out.write("\n");
      out.write("						<td align=\"middle\" class=\"separator\" valign=\"middle\">\n");
      out.write("						</td>\n");

		} else {

      out.write("\n");
      out.write("						<td align=\"middle\" id=\"tdb_");
      out.print(UrlUtil.htmlEncode(buttons[i].getName()));
      out.write("\" class=\"");
      out.print(UrlUtil.htmlEncode(buttons[i].getStyleClass()));
      out.write("\" height=18>\n");
      out.write("							<a href=\"javascript:");
      out.print(UrlUtil.htmlEncode(buttons[i].getAction()));
      out.write('(');
      out.write('\'');
      out.write('b');
      out.print(i);
      out.write("', '");
      out.print(UrlUtil.htmlEncode(buttons[i].getParam()));
      out.write("');\" \n");
      out.write("							   onmouseover=\"javascript:setWindowStatus('");
      out.print(UrlUtil.htmlEncode(buttons[i].getName()));
      out.write("');return true;\" \n");
      out.write("							   onmouseout=\"window.status='';\"\n");
      out.write("							   id=\"b");
      out.print(i);
      out.write("\">\n");
      out.write("							   <img src=\"");
      out.print(UrlUtil.htmlEncode(buttons[i].getImage()));
      out.write("\" \n");
      out.write("									alt='");
      out.print(UrlUtil.htmlEncode(buttons[i].getTooltip()));
      out.write("' \n");
      out.write("									title='");
      out.print(UrlUtil.htmlEncode(buttons[i].getTooltip()));
      out.write("'\n");
      out.write("									border=\"0\"\n");
      out.write("									id=\"");
      out.print(UrlUtil.htmlEncode(buttons[i].getName()));
      out.write("\">\n");
      out.write("							</a>\n");
      out.write("						</td>\n");

		}
	}

      out.write("				\n");
      out.write("					</tr>\n");
      out.write("					</table>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("		</table> \n");
      out.write("		</div>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
// special case for content toolbar - internally used live help frame
if ("content".equals(request.getParameter("toolbar"))) {

      out.write("\n");
      out.write("    <iframe name=\"liveHelpFrame\" title=\"");
      out.print(ServletResources.getString("ignore", "liveHelpFrame", request));
      out.write("\" src=\"blank.html\" style=\"visibility:hidden\" tabindex=\"-1\" frameborder=\"no\" width=\"0\" height=\"0\" scrolling=\"no\">\n");
      out.write("    </iframe>\n");

}

      out.write("\n");
      out.write("\n");
      out.write("</body>     \n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
