/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.12
 * Generated at: 2024-11-13 15:47:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.advanced;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.eclipse.help.internal.webapp.data.*;
import org.eclipse.help.webapp.*;

public final class views_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/advanced/header.jsp", Long.valueOf(1725338750000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.eclipse.help.webapp");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.eclipse.help.internal.webapp.data");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 
request.setCharacterEncoding("UTF-8");
boolean isRTL = UrlUtil.isRTL(request, response);
String  direction = isRTL?"rtl":"ltr";

      out.write(" \n");
      out.write(" <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Frameset//EN\" \"http://www.w3.org/TR/html4/frameset.dtd\">\n");
      out.write("<!--\n");
      out.write(" ! Copyright (c) 2000, 2018 IBM Corporation and others.\n");
      out.write(" !\n");
      out.write(" ! This program and the accompanying materials \n");
      out.write(" ! are made available under the terms of the Eclipse Public License 2.0\n");
      out.write(" ! which accompanies this distribution, and is available at\n");
      out.write(" ! https://www.eclipse.org/legal/epl-2.0/\n");
      out.write(" !\n");
      out.write(" ! SPDX-License-Identifier: EPL-2.0\n");
      out.write(" ! \n");
      out.write(" ! Contributors:\n");
      out.write(" !     IBM Corporation - initial API and implementation\n");
      out.write(" -->");
      out.write('\n');
      out.write('\n');
 
	LayoutData data = new LayoutData(application,request, response);
	WebappPreferences prefs = data.getPrefs();
	AbstractView[] views = data.getViews();	

      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"");
      out.print(ServletResources.getString("locale", request));
      out.write("\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\n");
      out.write("<title>");
      out.print(ServletResources.getString("Views", request));
      out.write("</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/* need this one for Mozilla */\n");
      out.write("HTML { \n");
      out.write("	width:100%;\n");
      out.write("	height:100%;\n");
      out.write("	margin:0px;\n");
      out.write("	padding:0px;\n");
      out.write("	border:0px;\n");
      out.write(" }\n");
      out.write("\n");
      out.write("BODY {\n");
      out.write("	margin:0px;\n");
      out.write("	padding:0px;\n");
      out.write("	/* Mozilla does not like width:100%, so we set height only */\n");
      out.write("	height:100%;\n");
      out.write("	position:relative; /* Needed for Safari */\n");
      out.write("}\n");
      out.write("\n");
      out.write("IFRAME {\n");
      out.write("	width:100%;\n");
      out.write("	height:100%;\n");
      out.write("	position:absolute; /* Needed for Safari */\n");
      out.write("	top:0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hidden {\n");
      out.write("	visibility:hidden;\n");
      out.write("	width:0;\n");
      out.write("	height:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".visible {\n");
      out.write("	visibility:visible;\n");
      out.write("	width:100%;\n");
      out.write("	height:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\" src=\"views.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var activityFiltering = ");
      out.print((new ActivitiesData(application, request, response)).isActivityFiltering()?"true":"false");
      out.write(";\n");
      out.write("var displayShowAllConfirmation = ");
      out.print(prefs.isDontConfirmShowAll()?"false":"true");
      out.write(";\n");
      out.write("\n");
      out.write("function confirmShowAll()\n");
      out.write("{\n");

if (data.isIE()){

      out.write("\n");
      out.write("	var l = top.screenLeft + (top.document.body.clientWidth - w) / 2;\n");
      out.write("	var t = top.screenTop + (top.document.body.clientHeight - h) / 2;\n");

} else {

      out.write("\n");
      out.write("	var l = top.screenX + (top.innerWidth - w) / 2;\n");
      out.write("	var t = top.screenY + (top.innerHeight - h) / 2;\n");

}

      out.write("\n");
      out.write("	// move the dialog just a bit higher than the middle\n");
      out.write("	if (t-50 > 0) t = t-50;\n");
      out.write("	\n");
      out.write("	window.location=\"javascript://needModal\";\n");
      out.write("	confirmShowAllDialog = window.open(\"confirmShowAll.jsp\", \"confirmShowAllDialog\", \"resizable=no,height=\"+h+\",width=\"+w+\",left=\"+l+\",top=\"+t );\n");
      out.write("	confirmShowAllDialog.focus(); \n");
      out.write("}\n");
      out.write("\n");
      out.write("function selectScope() \n");
      out.write("{\n");

if (data.isIE()){

      out.write("\n");
      out.write("	var l = top.screenLeft + (top.document.body.clientWidth - w) / 2;\n");
      out.write("	var t = top.screenTop + (top.document.body.clientHeight - h) / 2;\n");

} else {

      out.write("\n");
      out.write("	var l = top.screenX + (top.innerWidth - w) / 2;\n");
      out.write("	var t = top.screenY + (top.innerHeight - h) / 2;\n");

}

      out.write("\n");
      out.write("	// move the dialog just a bit higher than the middle\n");
      out.write("	if (t-50 > 0) t = t-50;\n");
      out.write("	\n");
      out.write("	window.location=\"javascript://needModal\";\n");
      out.write("	selectScopeDialog = window.open(\"selectScope.jsp\", \"selectScopeDialog\", \"resizable=no,height=\"+h+\",width=\"+w+\",left=\"+l+\",top=\"+t );\n");
      out.write("	selectScopeDialog.focus(); \n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("   \n");
      out.write("<body dir=\"");
      out.print(direction);
      out.write("\" tabIndex=\"-1\" onunload=\"closeConfirmShowAllDialog()\">\n");

	for (int i=0; i<views.length; i++) 
	{
	    if (views[i].isVisible()) {
		    // normally we would hide the views first, but mozilla needs all iframes to be visible to load 
		    // other frames
		    String className =  data.getVisibleView().equals(views[i].getName()) ? "visible" : "hidden";

      out.write("\n");
      out.write(" 	<iframe frameborder=\"0\" \n");
      out.write(" 		    class=\"");
      out.print(className);
      out.write("\"  \n");
      out.write(" 		    name=\"");
      out.print(views[i].getName());
      out.write("\"\n");
      out.write(" 		    title=\"");
      out.print(ServletResources.getString("ignore", views[i].getName(), request));
      out.write("\"\n");
      out.write(" 		    id=\"");
      out.print(views[i].getName());
      out.write("\" \n");
      out.write(" 		    scrolling=\"no\"\n");
      out.write(" 		    src='");
      out.print("view.jsp?view="+views[i].getName()+(request.getQueryString()==null?"":("&"+UrlUtil.htmlEncode(request.getQueryString()))));
      out.write("'>\n");
      out.write(" 	</iframe> \n");

        }
	}

      out.write("	\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
